### PR TITLE
Added darkmode in home page

### PR DESCRIPTION
**Pull request by tfsumon**
Added module & improved core files code structure

- organized partials and removed partials and shortcodes that is added as modules.
- renamed video section shortcode for avoid conflict with video shortcode
- added automation scripts to update modules

### CODE REVIEW

**Comment by tfsumon** [comment]
You can safely ignore these code scanning results. Adding `go.mod` and `go.sum` files is necessary for Hugo modules to function properly.

CleanShot 2024-04-04 at 16 58 35

**Comment by devopstoday11** [comment]
@tfsumon , Looks like whole website turned into darkmode in this sample.  Was it supposed to? Will I still be able to customize colors on every page as I want, is that functionality still working?

**Comment by tfsumon** [comment]
Hi @chandu-intelops !

You can customize the page color similarly to how you did before. I just made some global color changes.

Regarding dark mode, you mentioned wanting it on the homepage. However, implementing it solely for the homepage would require rework later for the entire site. To avoid this, I've implemented dark mode with the whole site in mind.

The rest of the pages shouldn't take long to adjust for dark mode, and I'll handle that after our vacation.

**Comment by devopstoday11** [comment]
@tfsumon 
I tested the dark mode you submitted. Somehow, it doesn't match the colors of the design I shared. Please verify the color codes. To make your life easy, I added PDF guidance in our chat on discord.

**Comment by tfsumon** [comment]
Thanks @devopstoday11 for testing dark mode! Checking colors vs your Discord PDF guidance.

**Comment by tfsumon** [comment]
Hi @devopstoday11,

I've updated the dark mode colors according to your specifications in the PDF. I'd appreciate your feedback on the changes.
Looking forward to hearing your thoughts!

Thank you.

**Comment by devopstoday11** [comment]
> Hi @devopstoday11,
> 
> I've updated the dark mode colors according to your specifications in the PDF. I'd appreciate your feedback on the changes. Looking forward to hearing your thoughts!
> 
> Thank you.

@tfsumon , saw the latest changes you did for whole site. Looks like you forgot for services page. 
Got to this in the URL and check: 
'''
/services-form/
'''

**Pull request merged**
