### PR TITLE
Added & modified existing layouts

### PR DESCRIPTION
**Pull request by tfsumon**
Added & modified layouts for following pages:

url - https://deploy-preview-383--intelops-website-nonprod.netlify.app/about/
markdown - content/english/about.md

url -  https://deploy-preview-383--intelops-website-nonprod.netlify.app/capten/
markdown - content/english/capten.md

url -  https://deploy-preview-383--intelops-website-nonprod.netlify.app/services/financial-services/
markdown - content/english/services/financial-services.md

url -  https://deploy-preview-383--intelops-website-nonprod.netlify.app/services/cloud-native-services-and-solutions/
markdown - content/english/services/cloud-native-services-and-solutions.md

### CODE REVIEW

**Comment by devopstoday11** [comment]
@tfsumon 
What about Homepage and the menu items and other pages as per new design? I need all together.

**Comment by tfsumon** [comment]
@chandu-intelops 

I've updated the homepage and menu items, as well as other pages, according to the new design. Could you please clarify which pages or sections are not aligned with the design?

**Comment by devopstoday11** [comment]
@tfsumon , The menu items were changed. 
For example, the Platform doesn't have a drop-down anymore. And there is a new design given to the single Platform page. Did you check it?

**Comment by devopstoday11** [comment]
Instead of this 383 PR merging this 384 PR - https://github.com/intelops/website/pull/384

**Pull request closed without merging**
