### PR TITLE
added working lottiefile 

### PR DESCRIPTION
**Pull request by devopstoday11**

### CODE REVIEW

**Comment by devopstoday11** [comment]
@tfsojon 
I added new lottiefile which I tested in my local. In my local, the animation is loading fine and working fine. But when deployed on netlify it's not working. Please check the rendering issue. 

here is the netlify preview  URL - https://deploy-preview-212--intelops-website-prod.netlify.app/ 

take the lottiefile file " homepage_concept_v4.json " from this PR and try in your local and see the difference.

**Comment by tfsojon** [comment]
It's working I thing.
[Intelops.webm](https://github.com/intelops/website/assets/87603786/b6681ef4-4ac3-4bf7-a4b3-3212d0687ecb)

**Comment by devopstoday11** [comment]
> It's working I thing. [Intelops.webm](https://github.com/intelops/website/assets/87603786/b6681ef4-4ac3-4bf7-a4b3-3212d0687ecb)

It's not working @tfsojon. Try in your local then you'll see the difference.  The animation is not full & not properly loading on netlify live.  But in my local, it's working fine.

**Comment by tfsojon** [comment]
@devopstoday11 
update the `netlify.toml` file with this. it will fix the lottiefile issue

```
[build]
  publish = "public"
  command = "hugo --gc"
  
[build.environment]
  HUGO_VERSION = "0.115.1"
  GO_VERSION = "1.20"
  HUGO_BASEURL = "/"

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.

[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "same-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

```

**Comment by devopstoday11** [comment]
@tfsojon , it's good now.  But page load time has increased. Could you optimize the website performance please?

**Pull request merged**
